Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -18,20 +18,29 @@ pipeline {
                 echo "build success and ok"
                 }
             }
-         stage('post') {
-          success {
-            // Actions to perform when the pipeline succeeds
-            echo 'Build successful!'
-
-            // You can add additional steps here, such as sending notifications or triggering downstream jobs
-        }
-
-          failure {
-            // Actions to perform when the pipeline fails
-            echo 'Build failed!'
-
-            // You can add additional steps here, such as sending notifications or triggering downstream jobs
-        }
-    }
+         stage('Test') {  
+             steps {  
+                 sh 'echo "Fail!"; exit 1'  
+             }  
+         }  
+     }  
+     post {  
+         always {  
+             echo 'This will always run'  
+         }  
+         success {  
+             echo 'This will run only if successful'  
+         }  
+         failure {  
+             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: '', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "abhay4291@gmail.com";  
+         }  
+         unstable {  
+             echo 'This will run only if the run was marked as unstable'  
+         }  
+         changed {  
+             echo 'This will run only if the state of the Pipeline has changed'  
+             echo 'For example, if the Pipeline was previously failing but is now successful'  
+         }  
+}
         }
      }
